### ISSUE TITLE
尊敬的开发者您好  提交一个测试bug

### ISSUE THREAD

**Issue by passwordhk** [CCmahua/ChatTTS-Enhanced#2]
我的系统环境是  intel 13400F  搭配Amd显卡，在测试环境中发现无法正常自定义音色，有以下报错 

Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

请问解决方案是去买个显卡吗  哭死

**Comment by CCmahua** [comment]
processors/audio_processor.py第38行修改为
```
 rand_spk = torch.load(emb_upload_path,map_location=torch.device('cpu'))
```

  processors/config_processor.py的save_config函数改为
```
def save_config(name,con_params: ConfigParams):
    con_params.tensor = get_seed_tensor(con_params.audio_seed)
    if con_params.custom_emb and con_params.emb_path is not None:
        con_params.tensor = torch.load(con_params.emb_path, map_location=torch.device('cpu'))
    save_path = os.path.join(get_path('CONFIG_DIR'), f"{name}.pt")
    torch.save(con_params, save_path)
    return f"配置保存至 {save_path}"
```

**Comment by passwordhk** [comment]
已解决问题，十分感谢开发者！
